### ISSUE TITLE
using wagl out of a swarm context

### ISSUE THREAD

**Issue by docteurklein** [ahmetalpbalkan/wagl#3] opened 2015-12-09 22:14 UTC
I'd like to try wagl out of a cluster by using

```
docker run --net host --restart=always -p 53:53/udp --name=dns ahmet/wagl wagl --swarm "127.0.0.1:2375"
```

The problem is that every entry resolves to 0.0.0.0:

```
 dig @localhost _web._tcp.swarm SRV             

; <<>> DiG 9.10.3 <<>> @localhost _web._tcp.swarm SRV
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19899
;; flags: qr aa rd; QUERY: 1, ANSWER: 10, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;_web._tcp.swarm.       IN  SRV

;; ANSWER SECTION:
_web._tcp.swarm.    0   IN  SRV 1 1 32770 0.0.0.0.
_web._tcp.swarm.    0   IN  SRV 1 1 32772 0.0.0.0.
_web._tcp.swarm.    0   IN  SRV 1 1 32769 0.0.0.0.
_web._tcp.swarm.    0   IN  SRV 1 1 32768 0.0.0.0.
_web._tcp.swarm.    0   IN  SRV 1 1 32774 0.0.0.0.
_web._tcp.swarm.    0   IN  SRV 1 1 32776 0.0.0.0.
_web._tcp.swarm.    0   IN  SRV 1 1 32775 0.0.0.0.
_web._tcp.swarm.    0   IN  SRV 1 1 32773 0.0.0.0.
_web._tcp.swarm.    0   IN  SRV 1 1 32777 0.0.0.0.
_web._tcp.swarm.    0   IN  SRV 1 1 32771 0.0.0.0.

;; Query time: 0 msec
;; SERVER: ::1#53(::1)
;; WHEN: Wed Dec 09 23:11:30 CET 2015
;; MSG SIZE  rcvd: 453

```

Any idea how I could circumvent that?
I know it's not really the goal of this project, but could there be a "mode" where wagl would actually use the container ip instead of the host ip ?

**Comment by ahmetb** [comment] 2015-12-09 23:39
@docteurklein Hmm I cannot reproduce this by starting wagl like you mentioned. Are you running `dig` inside the container or outside the container (it should not matter but anyways). It works both inside the container and outside the container for me with the same `dig @localhost` command.

Can you please check the logs (`docker logs -f dns`) if there's some warning going on?

Also, can you please give the `docker -H :2375 ps` of your swarm cluster? If we're seeing 0.0.0.0, there's either a parsing error going on or swarm is returning IP addresses of these containers as 0.0.0.0.

**Comment by docteurklein** [comment] 2015-12-10 07:57
@ahmetalpbalkan I was running dig outside the container. 
In fact, when used on the host, it works well, since the service is indeed listnening on the local loop interface (using -P to expose the port on the host).

It's only when inside a container that 0.0.0.0 does not work anymore.

The logs seemed ok, no warning, (only the wagl container has no DNS name, but that's logical):

```
2015/12/10 07:54:21 Refreshing DNS records...
2015/12/10 07:54:21 Found 1 tasks are not eligible for DNS records:
2015/12/10 07:54:21     - addb4ab17ea46565e32300994047f75c4179f3919725170f23a847cf0e06c550: has no DNS name specified (or not configured for DNS)
2015/12/10 07:54:21 Tasks with DNS records: 4
2015/12/10 07:54:21     +RR: A web.swarm. 0.0.0.0
2015/12/10 07:54:21     +RR: SRV _web._tcp.swarm. 0.0.0.0:32774
2015/12/10 07:54:21     +RR: SRV _web._tcp.swarm. 0.0.0.0:32775
2015/12/10 07:54:21     +RR: A web.swarm. 0.0.0.0
2015/12/10 07:54:21     +RR: SRV _web._tcp.swarm. 0.0.0.0:32772
2015/12/10 07:54:21     +RR: SRV _web._tcp.swarm. 0.0.0.0:32773
2015/12/10 07:54:21     +RR: A web.swarm. 0.0.0.0
2015/12/10 07:54:21     +RR: SRV _web._tcp.swarm. 0.0.0.0:32770
2015/12/10 07:54:21     +RR: SRV _web._tcp.swarm. 0.0.0.0:32771
2015/12/10 07:54:21     +RR: A web.swarm. 0.0.0.0
2015/12/10 07:54:21     +RR: SRV _web._tcp.swarm. 0.0.0.0:32769
2015/12/10 07:54:21     +RR: SRV _web._tcp.swarm. 0.0.0.0:32768
2015/12/10 07:54:21 Successfully refreshed records.
```

`docker ps` indeed lists them as 0.0.0.0:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                           NAMES
e6f84391f6f7        nginx               "nginx -g 'daemon off"   2 minutes ago       Up 2 minutes        0.0.0.0:32775->80/tcp, 0.0.0.0:32774->443/tcp   lonely_meninsky
b8f17d3d0b36        nginx               "nginx -g 'daemon off"   2 minutes ago       Up 2 minutes        0.0.0.0:32773->80/tcp, 0.0.0.0:32772->443/tcp   suspicious_hypatia
fc48345f172a        nginx               "nginx -g 'daemon off"   2 minutes ago       Up 2 minutes        0.0.0.0:32771->80/tcp, 0.0.0.0:32770->443/tcp   backstabbing_bell
0d8be30a53b2        nginx               "nginx -g 'daemon off"   2 minutes ago       Up 2 minutes        0.0.0.0:32769->80/tcp, 0.0.0.0:32768->443/tcp   compassionate_swanson
addb4ab17ea4        ahmet/wagl          "wagl --swarm 127.0.0"   3 minutes ago       Up 3 minutes                                                        dns
```

PS: the containers labeled as "web" in my example where ran using:

```
docker run -d -P -l dns.service=web nginx
```

**Comment by ahmetb** [comment] 2015-12-10 08:10
you're not targeting swarm manager here, you are giving wagl a docker engine directly. You should not do that. :-) it is only for clusters.

**Comment by docteurklein** [comment] 2015-12-10 08:25
yeah I know, that was the goal of this issue :) to know if there was a way to use it this way.

I could use the random "load balancing" feature you provide even outside a swarm cluster.

**Comment by docteurklein** [comment] 2015-12-10 08:35
In fact, there is only a few places where the hostIp is used:

https://github.com/ahmetalpbalkan/wagl/search?utf8=%E2%9C%93&q=HostIP

Do you think it would worth it to make wagl a DNS for docker engines too?
I can totally see a use case even without a swarm cluster.

**Comment by ahmetb** [comment] 2015-12-10 17:29
Will this be any different than container linking (docker run --link)? It already does the same thing for containers on the same host.

**Comment by ahmetb** [comment] 2015-12-10 20:03
Also there's not much we can do, if docker API gives us 0.0.0.0 as the address, that's it. I wouldn't prefer adding such an IP resolving feature simply because (1) wagl is not designed for single host (2) doing load balancing on a single host is highly unusual (3) there's no easy way workaround to this, and it will probably defeat minimalism aspect of wagl, this is not intended to solve everything. :)

**Comment by docteurklein** [comment] 2015-12-11 08:32
I definitely agree it does not worth the complication for wagl.

but let me still discuss the advantages :) :

links are not compatible with networking (and soon to be deprecated).
Using docker-compose, links can lead to circular references, avoiding some configs.
links are static: once a container is dead, the resolved ip is wrong for other containers.

single-host load-balancing might be unusual, but it would allow to scale a nginx fcgi backend pool very easily (f.e).

I'm not sure, but what I proposed was simply to replace the HostIp with the container.Ip, if you enabled wagl with `--single-host` f.e.

Anyway, that was just my 2 cents :)
I definitely understand that you have no plan to implement that, I was just wondering if what I said made any sense.

Thanks!
Flo

**Comment by ahmetb** [comment] 2015-12-11 19:52
@docteurklein if you send a pull request, we can discuss. :)

**Comment by ahmetb** [comment] 2016-02-08 23:37
Closing due to inactivity.

**Closed as completed by ahmetb** 2016-02-08 23:37 UTC
